<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- BenchmarkDotNet requires an optimized build to produce meaningful numbers. -->
    <Optimize>true</Optimize>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

</Project>
